name: concrete-strength-ui
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - adwaita-icon-theme=49.0=unix_0
  - altair=4.2.2=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - atk-1.0=2.38.0=h4bec284_2
  - attrs=24.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - brotli=1.2.0=hb27157a_0
  - brotli-bin=1.2.0=h5c1846c_0
  - bzip2=1.0.8=h500dc9f_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h950ec3b_0
  - catboost=1.0.6=py38h50d1736_1
  - certifi=2024.8.30=pyhd8ed1ab_0
  - contourpy=1.1.1=py38h15a1a5b_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - decorator=4.4.2=py_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - epoxy=1.5.10=h8616949_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h37eeddb_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.53.1=py38hc718529_0
  - freetype=2.14.1=h694c41f_0
  - fribidi=1.0.16=h8616949_0
  - gdk-pixbuf=2.44.4=h07555a4_0
  - glib-tools=2.86.1=h8650975_1
  - graphite2=1.3.14=h21dd04a_2
  - graphviz=13.1.2=h42bfd48_0
  - gtk3=3.24.43=h5e629aa_6
  - gts=0.7.6=h53e17e3_4
  - harfbuzz=12.2.0=hc5d3ef4_0
  - hicolor-icon-theme=0.17=h694c41f_2
  - icu=75.1=h120a0e1_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=5.5.5=py38h6c79ece_0
  - ipython=7.33.0=py38h50d1736_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py38h50d1736_0
  - kiwisolver=1.4.5=py38h15a1a5b_1
  - krb5=1.21.3=h37d8d59_0
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hcca01a6_1
  - libblas=3.9.0=20_osx64_openblas
  - libbrotlicommon=1.2.0=h105ed1c_0
  - libbrotlidec=1.2.0=h660c9da_0
  - libbrotlienc=1.2.0=h2338291_0
  - libcblas=3.9.0=20_osx64_openblas
  - libcxx=21.1.5=h3d58e20_0
  - libdeflate=1.25=h517ebb2_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.5.2=h750e83c_0
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - libgd=2.3.3=h8555400_11
  - libgfortran=15.2.0=h306097a_1
  - libgfortran5=15.2.0=h336fb69_1
  - libglib=2.86.1=h6ca3a76_1
  - libiconv=1.18=h57a12c2_2
  - libintl=0.25.1=h3184127_1
  - libjpeg-turbo=3.1.2=h8616949_0
  - liblapack=3.9.0=20_osx64_openblas
  - liblzma=5.8.1=hd471939_2
  - liblzma-devel=5.8.1=hd471939_2
  - libopenblas=0.3.25=openmp_hfef2a42_0
  - libpng=1.6.50=h84aeda2_1
  - libprotobuf=3.20.1=hbc0c0cd_4
  - librsvg=2.60.0=h2da6fc3_0
  - libsodium=1.0.18=hbcb3906_1
  - libsqlite=3.51.0=h86bffb9_0
  - libtiff=4.7.1=ha0a348c_1
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxgboost=1.6.1=cpu_h8296f74_1
  - libxml2-16=2.15.1=ha1d9b0f_0
  - libzlib=1.3.1=hd23fc13_2
  - lightgbm=3.3.2=py38hffa2396_0
  - llvm-openmp=21.1.5=h472b3d1_0
  - markupsafe=2.1.5=py38hae2e43d_0
  - matplotlib-base=3.7.1=py38hcb346ec_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h0622a9a_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=1.21.4=py38h49b9922_0
  - openjpeg=2.5.4=h87e8dc5_0
  - openssl=3.5.4=h230baf5_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.0.0=py38hec72209_0
  - pango=1.56.4=h6ef8af8_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.46=ha3e7e28_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py38hf802781_0
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.46.4=ha059160_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - plotly=5.24.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.43=pyha770c72_0
  - protobuf=3.20.1=py38h1c67a95_0
  - pthread-stubs=0.4=h00291cd_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py-xgboost=1.6.1=cpu_py38he866dac_1
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - python=3.8.20=h4f978b9_2_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-graphviz=0.20.3=pyhe28f650_1
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.8=8_cp38
  - pytz=2024.2=pyhd8ed1ab_0
  - pyzmq=24.0.1=py38h0b711fd_0
  - readline=8.2=h7cca4af_2
  - referencing=0.35.1=pyhd8ed1ab_0
  - rpds-py=0.20.0=py38h2c15f49_0
  - scikit-learn=1.0.1=py38h37f3bb3_3
  - scipy=1.9.3=py38hfb8b963_2
  - setuptools=75.3.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - tenacity=9.0.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=hf689a15_2
  - toolz=1.0.0=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - unicodedata2=15.1.0=py38hcafd530_0
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - xgboost=1.6.1=cpu_py38h02b2a6e_1
  - xorg-libxau=1.0.12=h6e16a3a_0
  - xorg-libxdmcp=1.1.5=h00291cd_0
  - xz=5.8.1=h357f2ed_2
  - xz-gpl-tools=5.8.1=h357f2ed_2
  - xz-tools=5.8.1=hd471939_2
  - zeromq=4.3.5=hde137ed_4
  - zipp=3.21.0=pyhd8ed1ab_0
  - zstd=1.5.7=h8210216_2
  - pip:
      - backports-zoneinfo==0.2.1
      - blinker==1.8.2
      - cachetools==5.5.2
      - charset-normalizer==3.4.4
      - click==8.1.8
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.11
      - importlib-metadata==8.5.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - pickle-mixin==1.0.2
      - pyarrow==17.0.0
      - pydeck==0.9.1
      - pygments==2.19.2
      - pympler==1.1
      - requests==2.32.4
      - rich==14.2.0
      - semver==3.0.4
      - smmap==5.0.2
      - streamlit==1.12.0
      - streamlit-option-menu==0.3.2
      - toml==0.10.2
      - tornado==6.4.2
      - typing-extensions==4.13.2
      - tzlocal==5.2
      - urllib3==2.2.3
      - validators==0.34.0
prefix: /Users/pinkhathacker/opt/anaconda3/envs/concrete-strength-ui
